name: Push Docker image to OCI Container Registry

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to OCI Container Registry
      uses: docker/login-action@v1
      with:
        registry: jed.ocir.io
        username: ${{ secrets.OCI_USERNAME }}
        password: ${{ secrets.OCI_AUTH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: jed.ocir.io/axnfm4jb3i73/nodejs-repo:latest
